version: 0.0
os: linux

files:
  - source: /
    destination: /tmp/deployment

hooks:
  AfterInstall:
    - location: scripts/deploy_laravel.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300 # Adjust timeout as needed
      runas: root
